import NavBar from "@/components/NavBar/NavBar"
import "../styles/styles.scss"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Suhipletos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es" data-bs-theme="dark">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
